// Mocks generated by Mockito 5.4.4 from annotations
// in bilhetinhos/test/modules/home/domain/use_cases/fetch_all_pots_by_user_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:bilhetinhos/modules/auth/domain/models/user_model.dart' as _i5;
import 'package:bilhetinhos/modules/auth/domain/repositories/user_data_repository.dart'
    as _i3;
import 'package:bilhetinhos/modules/home/domain/errors/fetch_pots_errors.dart'
    as _i2;
import 'package:bilhetinhos/modules/home/domain/models/pot_model.dart' as _i7;
import 'package:bilhetinhos/modules/home/domain/repositories/pot_repository.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePotsErrors_0 extends _i1.SmartFake implements _i2.PotsErrors {
  _FakePotsErrors_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserDataRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserDataRepository extends _i1.Mock
    implements _i3.UserDataRepository {
  @override
  _i4.Future<_i5.UserDataModel?> getCurrentUserData() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserData,
          [],
        ),
        returnValue: _i4.Future<_i5.UserDataModel?>.value(),
        returnValueForMissingStub: _i4.Future<_i5.UserDataModel?>.value(),
      ) as _i4.Future<_i5.UserDataModel?>);
}

/// A class which mocks [PotRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPotRepository extends _i1.Mock implements _i6.PotRepository {
  @override
  _i4.Future<(List<_i7.PotModel>, _i2.PotsErrors)> getPotsByUser(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPotsByUser,
          [userId],
        ),
        returnValue: _i4.Future<(List<_i7.PotModel>, _i2.PotsErrors)>.value((
          <_i7.PotModel>[],
          _FakePotsErrors_0(
            this,
            Invocation.method(
              #getPotsByUser,
              [userId],
            ),
          )
        )),
        returnValueForMissingStub:
            _i4.Future<(List<_i7.PotModel>, _i2.PotsErrors)>.value((
          <_i7.PotModel>[],
          _FakePotsErrors_0(
            this,
            Invocation.method(
              #getPotsByUser,
              [userId],
            ),
          )
        )),
      ) as _i4.Future<(List<_i7.PotModel>, _i2.PotsErrors)>);
}
